#!/usr/bin/env python3
"""Generate the popularity-ranked candidate list for the 1000-source expansion.

Popularity sources (ordered): GitHub star counts via the search API (30/min unauth,
cached), plus a hand-curated tier-0 list of major SaaS/cloud docs.

Output: /tmp/sources/candidates.jsonl — JSON lines in popularity order.
"""
import json, time, urllib.request, urllib.error

UA = {"User-Agent": "documesh-source-audit/1.0", "Accept": "application/vnd.github+json"}

# ── Tier 0: major hosted/SaaS/cloud developer docs (popularity = market adoption) ──
TIER0_SAAS = [
    # id, name, docs origin, repo (if any), license basis
    ("react", "React", "https://react.dev", "facebook/react", "MIT (docs CC-BY-4.0)"),
    ("vuejs", "Vue.js", "https://vuejs.org", "vuejs/core", "MIT (docs CC-BY-NC-SA — check)"),
    ("angular", "Angular", "https://angular.dev", "angular/angular", "MIT"),
    ("svelte", "Svelte", "https://svelte.dev", "sveltejs/svelte", "MIT"),
    ("nextjs", "Next.js", "https://nextjs.org/docs", "vercel/next.js", "MIT"),
    ("nuxt", "Nuxt", "https://nuxt.com", "nuxt/nuxt", "MIT"),
    ("astro", "Astro", "https://docs.astro.build", "withastro/astro", "MIT"),
    ("sveltekit", "SvelteKit", "https://kit.svelte.dev", "sveltejs/kit", "MIT"),
    ("remix", "Remix", "https://remix.run", "remix-run/remix", "MIT"),
    ("gatsby", "Gatsby", "https://www.gatsbyjs.com/docs", "gatsbyjs/gatsby", "MIT"),
    ("typescript", "TypeScript", "https://www.typescriptlang.org/docs", "microsoft/TypeScript", "Apache-2.0"),
    ("tailwindcss", "Tailwind CSS", "https://tailwindcss.com/docs", "tailwindlabs/tailwindcss", "MIT"),
    ("vite", "Vite", "https://vite.dev", "vitejs/vite", "MIT"),
    ("webpack", "webpack", "https://webpack.js.org", "webpack/webpack", "MIT"),
    ("rollupjs", "Rollup", "https://rollupjs.org", "rollup/rollup", "MIT"),
    ("esbuild", "esbuild", "https://esbuild.github.io", "evanw/esbuild", "MIT"),
    ("babeljs", "Babel", "https://babeljs.io", "babel/babel", "MIT"),
    ("eslint", "ESLint", "https://eslint.org", "eslint/eslint", "MIT"),
    ("prettier", "Prettier", "https://prettier.io", "prettier/prettier", "MIT"),
    ("vitest", "Vitest", "https://vitest.dev", "vitest-dev/vitest", "MIT"),
    ("jestjs", "Jest", "https://jestjs.io", "jestjs/jest", "MIT"),
    ("playwright", "Playwright", "https://playwright.dev", "microsoft/playwright", "Apache-2.0"),
    ("cypress", "Cypress", "https://docs.cypress.io", "cypress-io/cypress", "MIT"),
    ("storybook", "Storybook", "https://storybook.js.org", "storybookjs/storybook", "MIT"),
    ("nodejs", "Node.js", "https://nodejs.org/docs", "nodejs/node", "MIT"),
    ("denoland", "Deno", "https://docs.deno.com", "denoland/deno", "MIT"),
    ("bun", "Bun", "https://bun.com", "oven-sh/bun", "MIT"),
    ("expressjs", "Express", "https://expressjs.com", "expressjs/express", "MIT"),
    ("fastify", "Fastify", "https://fastify.dev", "fastify/fastify", "MIT"),
    ("nestjs", "NestJS", "https://docs.nestjs.com", "nestjs/nest", "MIT"),
    ("hapi", "hapi", "https://hapi.dev", "hapijs/hapi", "BSD-3"),
    ("koa", "Koa", "https://koajs.com", "koajs/koa", "MIT"),
    ("adonisjs", "AdonisJS", "https://adonisjs.com", "adonisjs/core", "MIT"),
    ("redwood", "RedwoodJS", "https://redwoodjs.com", "redwoodjs/redwood", "MIT"),
    ("blitzjs", "Blitz.js", "https://blitzjs.com", "blitz-js/blitz", "MIT"),
    ("trpc", "tRPC", "https://trpc.io", "trpc/trpc", "MIT"),
    ("graphql", "GraphQL", "https://graphql.org", "graphql/graphql-spec", "MIT (spec)"),
    ("apollo", "Apollo GraphQL", "https://www.apollographql.com/docs", "apollographql/apollo-client", "MIT"),
    ("relay", "Relay", "https://relay.dev", "facebook/relay", "MIT"),
    ("prisma", "Prisma", "https://www.prisma.io/docs", "prisma/prisma", "Apache-2.0"),
    ("drizzle", "Drizzle ORM", "https://orm.drizzle.team", "drizzle-team/drizzle-orm", "Apache-2.0"),
    ("sequelize", "Sequelize", "https://sequelize.org", "sequelize/sequelize", "MIT"),
    ("typeorm", "TypeORM", "https://typeorm.io", "typeorm/typeorm", "MIT"),
    ("knexjs", "Knex", "https://knexjs.org", "knex/knex", "MIT"),
    ("mongoose", "Mongoose", "https://mongoosejs.com", "Automattic/mongoose", "MIT"),
    ("redis", "Redis", "https://redis.io/docs", "redis/redis", "RSAL/SSPL — EXCLUDED unless docs differ"),
    ("memcached", "memcached", "https://memcached.org", "memcached/memcached", "BSD"),
    ("postgres", "PostgreSQL", "https://www.postgresql.org/docs", "postgres/postgres", "PostgreSQL License"),
    ("mysql", "MySQL", "https://dev.mysql.com/doc", "mysql/mysql-server", "GPL-2.0 — docsTerms?"),
    ("sqlite", "SQLite", "https://sqlite.org/docs", "sqlite/sqlite", "Public domain"),
    ("mongodb", "MongoDB", "https://www.mongodb.com/docs", "mongodb/mongo", "SSPL — docs CC-BY-NC-SA?"),
    ("couchdb", "CouchDB", "https://docs.couchdb.apache.org", "apache/couchdb", "Apache-2.0"),
    ("ravendb", "RavenDB", "https://ravendb.net/docs", "ravendb/ravendb", "AGPL — check docs"),
    ("influxdb", "InfluxDB", "https://docs.influxdata.com", "influxdata/influxdb", "MIT/Apache"),
    ("clickhouse", "ClickHouse", "https://clickhouse.com/docs", "ClickHouse/ClickHouse", "Apache-2.0"),
    ("supabase", "Supabase", "https://supabase.com/docs", "supabase/supabase", "Apache-2.0"),
    ("appwrite", "Appwrite", "https://appwrite.io/docs", "appwrite/appwrite", "BSD-3"),
    ("pocketbase", "PocketBase", "https://pocketbase.io/docs", "pocketbase/pocketbase", "MIT"),
    ("firebase", "Firebase", "https://firebase.google.com/docs", "firebase/firebase-js-sdk", "Apache-2.0 (SDK)"),
    ("amplify", "AWS Amplify", "https://docs.amplify.aws", "aws-amplify/amplify-js", "Apache-2.0"),
    ("hasura", "Hasura", "https://hasura.io/docs", "hasura/graphql-engine", "Apache-2.0"),
    ("postgraphile", "PostGraphile", "https://www.graphile.org/postgraphile", "graphile/crystal", "MIT"),
    ("docker", "Docker", "https://docs.docker.com", "moby/moby", "Apache-2.0"),
    ("podman", "Podman", "https://docs.podman.io", "containers/podman", "Apache-2.0"),
    ("kubernetes", "Kubernetes", "https://kubernetes.io/docs", "kubernetes/kubernetes", "CC-BY-4.0 docs, Apache-2.0 code"),
    ("helm", "Helm", "https://helm.sh/docs", "helm/helm", "Apache-2.0"),
    ("kustomize", "Kustomize", "https://kubectl.kubernetes.io", "kubernetes-sigs/kustomize", "Apache-2.0"),
    ("istio", "Istio", "https://istio.io", "istio/istio", "Apache-2.0"),
    ("cilium", "Cilium", "https://docs.cilium.io", "cilium/cilium", "Apache-2.0"),
    ("linkerd", "Linkerd", "https://linkerd.io", "linkerd/linkerd2", "Apache-2.0"),
    ("calico", "Calico", "https://docs.tigera.io", "projectcalico/calico", "Apache-2.0"),
    ("fluxcd", "Flux", "https://fluxcd.io", "fluxcd/flux2", "Apache-2.0"),
    ("argocd", "Argo CD", "https://argo-cd.readthedocs.io", "argoproj/argo-cd", "Apache-2.0"),
    ("argo-workflows", "Argo Workflows", "https://argoproj.github.io", "argoproj/argo-workflows", "Apache-2.0"),
    ("crossplane", "Crossplane", "https://docs.crossplane.io", "crossplane/crossplane", "Apache-2.0"),
    ("opentelemetry", "OpenTelemetry", "https://opentelemetry.io", "open-telemetry", "Apache-2.0 / CC-BY-4.0 docs"),
    ("prometheus", "Prometheus", "https://prometheus.io/docs", "prometheus/prometheus", "Apache-2.0"),
    ("grafana", "Grafana", "https://grafana.com/docs", "grafana/grafana", "AGPL — docs CC-BY? check"),
    ("loki", "Grafana Loki", "https://grafana.com/docs/loki", "grafana/loki", "AGPL — docs? check"),
    ("jaeger", "Jaeger", "https://www.jaegertracing.io", "jaegertracing/jaeger", "Apache-2.0"),
    ("tempo", "Grafana Tempo", "https://grafana.com/docs/tempo", "grafana/tempo", "AGPL — check"),
    ("victoriametrics", "VictoriaMetrics", "https://docs.victoriametrics.com", "VictoriaMetrics/VictoriaMetrics", "Apache-2.0"),
    ("elastic", "Elasticsearch", "https://www.elastic.co/guide", "elastic/elasticsearch", "Apache-2.0 / SSPL dual"),
    ("opensearch", "OpenSearch", "https://docs.opensearch.org", "opensearch-project/OpenSearch", "Apache-2.0"),
    ("solr", "Apache Solr", "https://solr.apache.org/guide", "apache/solr", "Apache-2.0"),
    ("rabbitmq", "RabbitMQ", "https://www.rabbitmq.com/docs", "rabbitmq/rabbitmq-server", "MPL-2.0"),
    ("kafka", "Apache Kafka", "https://kafka.apache.org/documentation", "apache/kafka", "Apache-2.0"),
    ("nats", "NATS", "https://docs.nats.io", "nats-io/nats-server", "Apache-2.0"),
    ("pulsar", "Apache Pulsar", "https://pulsar.apache.org/docs", "apache/pulsar", "Apache-2.0"),
    ("nats", "NATS", "https://nats.io", "nats-io/nats-server", "Apache-2.0"),
    ("grpc", "gRPC", "https://grpc.io", "grpc/grpc", "Apache-2.0"),
    ("protobuf", "Protocol Buffers", "https://protobuf.dev", "protocolbuffers/protobuf", "BSD"),
    ("envoy", "Envoy", "https://www.envoyproxy.io", "envoyproxy/envoy", "Apache-2.0"),
    ("traefik", "Traefik", "https://doc.traefik.io", "traefik/traefik", "MIT"),
    ("caddyserver", "Caddy", "https://caddyserver.com/docs", "caddyserver/caddy", "Apache-2.0"),
    ("nginx", "NGINX", "https://nginx.org/en/docs", "nginx/nginx", "BSD-2"),
    ("haproxy", "HAProxy", "https://docs.haproxy.org", "haproxy/haproxy", "GPL-2.0 — docs?"),
    ("keepalived", "Keepalived", "https://www.keepalived.org", "acassen/keepalived", "GPL-2.0 — docs?"),
    ("terraform", "Terraform", "https://developer.hashicorp.com/terraform/docs", "hashicorp/terraform", "BUSL — docs proprietary, EXCLUDED"),
    ("opentofu", "OpenTofu", "https://opentofu.org/docs", "opentofu/opentofu", "MPL-2.0"),
    ("pulumi", "Pulumi", "https://www.pulumi.com/docs", "pulumi/pulumi", "Apache-2.0"),
    ("crossplane", "Crossplane", "https://docs.crossplane.io", "crossplane/crossplane", "Apache-2.0"),
    ("ansible", "Ansible", "https://docs.ansible.com", "ansible/ansible", "GPL-3.0 code, docs GPL?"),
    ("salt", "Salt", "https://docs.saltproject.io", "saltstack/salt", "Apache-2.0"),
    ("chef", "Chef Infra", "https://docs.chef.io", "chef/chef", "Apache-2.0"),
    ("puppet", "Puppet", "https://www.puppet.com/docs", "puppetlabs/puppet", "Apache-2.0"),
    ("vagrant", "Vagrant", "https://developer.hashicorp.com/vagrant/docs", "hashicorp/vagrant", "BUSL — EXCLUDED"),
    ("packer", "Packer", "https://developer.hashicorp.com/packer/docs", "hashicorp/packer", "BUSL — EXCLUDED"),
    ("nomad", "Nomad", "https://developer.hashicorp.com/nomad/docs", "hashicorp/nomad", "BUSL — EXCLUDED"),
    ("consul", "Consul", "https://developer.hashicorp.com/consul/docs", "hashicorp/consul", "BUSL — EXCLUDED"),
    ("vault", "Vault", "https://developer.hashicorp.com/vault/docs", "hashicorp/vault", "BUSL — EXCLUDED"),
    ("github", "GitHub", "https://docs.github.com", "cli/cli", "proprietary, agent-permitted?"),
    ("gitlab", "GitLab", "https://docs.gitlab.com", "gitlabhq/gitlabhq", "MIT (docs CC-BY-NC-SA?)"),
    ("bitbucket", "Bitbucket", "https://support.atlassian.com/bitbucket-cloud", None, "proprietary"),
    ("circleci", "CircleCI", "https://circleci.com/docs", None, "proprietary"),
    ("travis", "Travis CI", "https://docs.travis-ci.com", "travis-ci/travis-web", "proprietary"),
    ("jenkins", "Jenkins", "https://www.jenkins.io/doc", "jenkinsci/jenkins", "MIT"),
    ("tekton", "Tekton", "https://tekton.dev", "tektoncd/pipeline", "Apache-2.0"),
    ("spinnaker", "Spinnaker", "https://spinnaker.io/docs", "spinnaker/spinnaker", "Apache-2.0"),
    ("harbor", "Harbor", "https://goharbor.io/docs", "goharbor/harbor", "Apache-2.0"),
    ("artifactory", "JFrog Artifactory", "https://jfrog.com/help", None, "proprietary"),
    ("vercel", "Vercel", "https://vercel.com/docs", "vercel/vercel", "Apache-2.0 code, docs proprietary-agent-permitted"),
    ("netlify", "Netlify", "https://docs.netlify.com", "netlify/developer-documentation", "proprietary, llms.txt agent-permitted"),
    ("render", "Render", "https://render.com/docs", "render-examples", "proprietary"),
    ("railway", "Railway", "https://docs.railway.com", None, "proprietary"),
    ("flyio", "Fly.io", "https://fly.io/docs", "superfly/flyctl", "Apache-2.0 (CLI)"),
    ("heroku", "Heroku", "https://devcenter.heroku.com", None, "proprietary"),
    ("digitalocean", "DigitalOcean", "https://docs.digitalocean.com", None, "proprietary, llms.txt agent-permitted"),
    ("linode", "Akamai/Linode", "https://www.linode.com/docs", None, "proprietary"),
    ("vultr", "Vultr", "https://www.vultr.com/docs", "vultr/govultr", "proprietary docs / Apache CLI"),
    ("scaleway", "Scaleway", "https://www.scaleway.com/en/docs", None, "proprietary"),
    ("hetzner", "Hetzner", "https://docs.hetzner.cloud", None, "proprietary"),
    ("ovh", "OVHcloud", "https://help.ovhcloud.com", None, "proprietary"),
    ("ibmcloud", "IBM Cloud", "https://cloud.ibm.com/docs", None, "proprietary, llms.txt"),
    ("oraclecloud", "Oracle Cloud", "https://docs.oracle.com/en-us/iaas", None, "proprietary (OTN)"),
    ("azure", "Microsoft Azure", "https://learn.microsoft.com/azure", "MicrosoftDocs/azure-docs", "CC-BY-4.0 docs!"),
    ("googlecloud", "Google Cloud", "https://cloud.google.com/docs", None, "CC-BY-4.0 docs"),
    ("awsdocs", "AWS", "https://docs.aws.amazon.com", "awsdocs (org)", "CC BY-NC? mostly awsdocs repos per-service"),
    ("alibabacloud", "Alibaba Cloud", "https://www.alibabacloud.com/help", "aliyun", "proprietary"),
    ("tencentcloud", "Tencent Cloud", "https://www.tencentcloud.com/document", None, "proprietary"),
    ("stripe", "Stripe", "https://docs.stripe.com", "stripe/stripe-node", "proprietary, llms.txt"),
    ("paypal", "PayPal", "https://developer.paypal.com/api", None, "proprietary"),
    ("square", "Square", "https://developer.squareup.com/docs", "square/square-nodejs-sdk", "Apache-2.0 SDK"),
    ("braintree", "Braintree", "https://developer.paypal.com/braintree/docs", "braintree/braintree_node", "MIT"),
    ("adyen", "Adyen", "https://docs.adyen.com", "Adyen/adyen-node-api-library", "MIT"),
    ("plaid", "Plaid", "https://plaid.com/docs", "plaid/plaid-node", "MIT"),
    ("twilio", "Twilio", "https://www.twilio.com/docs", "twilio/twilio-node", "MIT"),
    ("sendgrid", "SendGrid", "https://www.twilio.com/docs/sendgrid", "sendgrid/sendgrid-nodejs", "MIT"),
    ("mailgun", "Mailgun", "https://documentation.mailgun.com", "mailgun/mailgun-js", "MIT"),
    ("postmark", "Postmark", "https://postmarkapp.com/developer", "wildbit/postmark.js", "MIT"),
    ("sendinblue", "Brevo", "https://developers.brevo.com", None, "proprietary"),
    ("messagebird", "Bird (MessageBird)", "https://developers.messagebird.com", None, "proprietary"),
    ("vonage", "Vonage", "https://developer.vonage.com", "Vonage/vonage-node-sdk", "MIT"),
    ("slack", "Slack API", "https://api.slack.com", "slackapi/slack-sdk", "MIT"),
    ("discord", "Discord API", "https://discord.com/developers/docs", "discordjs/discord.js", "Apache-2.0"),
    ("telegram", "Telegram Bot API", "https://core.telegram.org/bots/api", "tdlib/td", "BSD"),
    ("whatsapp", "WhatsApp Business", "https://developers.facebook.com/docs/whatsapp", None, "proprietary"),
    ("notion", "Notion API", "https://developers.notion.com", "makenotion/notion-sdk-js", "MIT"),
    ("airtable", "Airtable", "https://airtable.com/developers/web", None, "proprietary"),
    ("linear", "Linear API", "https://developers.linear.app", "linear/linear", "proprietary (GraphQL API docs)"),
    ("jira", "Jira", "https://developer.atlassian.com/cloud/jira", None, "proprietary"),
    ("confluence", "Confluence", "https://developer.atlassian.com/cloud/confluence", None, "proprietary"),
    ("asana", "Asana API", "https://developers.asana.com", "Asana/asana", "MIT"),
    ("trello", "Trello", "https://developer.atlassian.com/cloud/trello", None, "proprietary"),
    ("monday", "monday.com API", "https://developer.monday.com", None, "proprietary"),
    ("hubspot", "HubSpot", "https://developers.hubspot.com", "HubSpot/hubspot-api-nodejs", "Apache-2.0"),
    ("salesforce", "Salesforce", "https://developer.salesforce.com/docs", "forcedotcom", "proprietary"),
    ("shopify", "Shopify", "https://shopify.dev/docs", "Shopify/shopify-api-js", "MIT"),
    ("woocommerce", "WooCommerce", "https://woocommerce.github.io/woocommerce-rest-api-docs", "woocommerce/woocommerce", "GPL-2.0? docs?"),
    ("magento", "Adobe Commerce", "https://developer.adobe.com/commerce", None, "proprietary"),
    ("bigcommerce", "BigCommerce", "https://developer.bigcommerce.com", None, "proprietary"),
    ("squarespace", "Squarespace", "https://developers.squarespace.com", None, "proprietary"),
    ("webflow", "Webflow", "https://developers.webflow.com", None, "proprietary"),
    ("wordpress", "WordPress", "https://developer.wordpress.org", "WordPress/wordpress-develop", "GPL-2.0 — docs GPL"),
    ("datadog", "Datadog", "https://docs.datadoghq.com", "DataDog/datadog-agent", "Apache-2.0 agent, docs proprietary"),
    ("newrelic", "New Relic", "https://docs.newrelic.com", "newrelic/newrelic-node-agent", "Apache-2.0"),
    ("sentry", "Sentry", "https://docs.sentry.io", "getsentry/sentry", "BSL/FSL — docs CC-BY?"),
    ("splunk", "Splunk", "https://docs.splunk.com", None, "proprietary"),
    ("sumologic", "Sumo Logic", "https://docs.sumologic.com", None, "proprietary"),
    ("dynatrace", "Dynatrace", "https://docs.dynatrace.com", None, "proprietary"),
    ("honeycomb", "Honeycomb", "https://docs.honeycomb.io", "honeycombio", "proprietary docs"),
    ("betterstack", "Better Stack", "https://betterstack.com/docs", None, "proprietary"),
    ("logtail", "Logtail", "https://betterstack.com/docs/logs", None, "proprietary"),
    ("pagerduty", "PagerDuty", "https://developer.pagerduty.com", "PagerDuty/pagerduty-api-nodejs", "MIT"),
    ("opsgenie", "Opsgenie", "https://support.atlassian.com/opsgenie/docs", None, "proprietary"),
    ("victorops", "Splunk On-Call", "https://docs.victorops.com", None, "proprietary"),
    ("statuspage", "Statuspage", "https://doers.statuspage.io", None, "proprietary"),
    ("cloudflare", "Cloudflare", "https://developers.cloudflare.com", "cloudflare/cloudflare-docs", "CC-BY-4.0 docs / MIT samples"),
    ("fastly", "Fastly", "https://www.fastly.com/documentation", "fastly", "proprietary docs, MIT SDKs"),
    ("akamai", "Akamai", "https://techdocs.akamai.com", "akamai", "proprietary"),
    ("zerssl", "Snyk", "https://docs.snyk.io", "snyk/cli", "Apache-2.0 CLI"),
    ("snyk", "Snyk", "https://docs.snyk.io", None, "proprietary docs"),
    ("okta", "Okta", "https://developer.okta.com/docs", "okta/okta-sdk-nodejs", "Apache-2.0"),
    ("auth0", "Auth0", "https://auth0.com/docs", "auth0", "proprietary docs"),
    ("clerk", "Clerk", "https://clerk.com/docs", "clerk/javascript", "MIT"),
    ("workos", "WorkOS", "https://workos.com/docs", "workos/workos-node", "MIT"),
    ("supertokens", "SuperTokens", "https://supertokens.com/docs", "supertokens/supertokens-core", "Apache-2.0"),
    ("keycloak", "Keycloak", "https://www.keycloak.org/documentation", "keycloak/keycloak", "Apache-2.0"),
    ("zitadel", "ZITADEL", "https://zitadel.com/docs", "zitadel/zitadel", "Apache-2.0"),
    ("ory", "Ory", "https://www.ory.sh/docs", "ory/kratos", "Apache-2.0"),
    ("logto", "Logto", "https://docs.logto.io", "logto-io/logto", "MPL-2.0"),
    ("kinde", "Kinde", "https://kinde.com/docs", None, "proprietary"),
    ("stytch", "Stytch", "https://stytch.com/docs", "stytchinc", "proprietary docs / MIT SDKs"),
]

TIER0_SAAS = [t for t in TIER0_SAAS if not t[0].startswith(("redis", "grafana", "woocommerce", "wordpress"))]

seen = set()
out = []
for sid, name, docs, repo, lic in TIER0_SAAS:
    if sid in seen:
        continue
    seen.add(sid)
    out.append({"id": sid, "name": name, "docs": docs, "repo": repo, "license": lic, "tier": 0})

with open("/tmp/sources/tier0.jsonl", "w") as f:
    for r in out:
        f.write(json.dumps(r) + "\n")
print(f"tier0 unique: {len(out)}")
